# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'flutter-ios-mix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flutter-ios-mix
  pod 'MBProgressHUD', '~> 0.9.2'

  target 'flutter-ios-mixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flutter-ios-mixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
